# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZenSync < Formula
  desc "Arc-like continuity for Zen Browser on macOS"
  homepage "https://github.com/gustavoguarda/zen-sync"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gustavoguarda/zen-sync/releases/download/v0.1.1/zen-sync_v0.1.1_darwin_amd64.tar.gz"
    sha256 "654220f988982380573bd3d859e0670c2992ff795ba69405e4ad16c2b1ac5758"

    define_method(:install) do
      bin.install "zen-sync"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gustavoguarda/zen-sync/releases/download/v0.1.1/zen-sync_v0.1.1_darwin_arm64.tar.gz"
    sha256 "61761395a065ed7c99115c99734171a71e95f3449292a956e5b8c1ac933cf1e7"

    define_method(:install) do
      bin.install "zen-sync"
    end
  end

  test do
    system "#{bin}/zen-sync", "version"
  end
end
