# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZenSync < Formula
  desc "Arc-like continuity for Zen Browser on macOS"
  homepage "https://github.com/gustavoguarda/zen-sync"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gustavoguarda/zen-sync/releases/download/v0.1.0/zen-sync_v0.1.0_darwin_amd64.tar.gz"
    sha256 "8c4dee39e1d605cca28c1909fe4da736361247d5ef4f07aad9381d02791da725"

    define_method(:install) do
      bin.install "zen-sync"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gustavoguarda/zen-sync/releases/download/v0.1.0/zen-sync_v0.1.0_darwin_arm64.tar.gz"
    sha256 "d25b5d250f30694a3038441844a8631daca4856ba9394d841a97f1cac194ec81"

    define_method(:install) do
      bin.install "zen-sync"
    end
  end

  test do
    system "#{bin}/zen-sync", "version"
  end
end
