# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZenSync < Formula
  desc "Arc-like continuity for Zen Browser on macOS"
  homepage "https://github.com/gustavoguarda/zen-sync"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gustavoguarda/zen-sync/releases/download/v0.1.2/zen-sync_v0.1.2_darwin_amd64.tar.gz"
    sha256 "1fbea118cd8eddf319c12bcc4342e5c2cdfa857155368f895017646a45f50ac4"

    define_method(:install) do
      bin.install "zen-sync"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gustavoguarda/zen-sync/releases/download/v0.1.2/zen-sync_v0.1.2_darwin_arm64.tar.gz"
    sha256 "c3fc34e828d3d8727ecc3f30c9321db8cdfc33fd84623d3de14fa83f116ec0ce"

    define_method(:install) do
      bin.install "zen-sync"
    end
  end

  def post_install
    config_path = "#{ENV["HOME"]}/.config/zen-sync/config.toml"
    if File.exist?(config_path)
      system bin/"zen-sync", "ensure-installation"
    end
  end

  test do
    system "#{bin}/zen-sync", "version"
  end
end
